//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BS_23.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BS_comment_parent_t
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BS_comment_parent_t()
        {
            this.BS_dislike_parent_t = new HashSet<BS_dislike_parent_t>();
            this.BS_like_parent_t = new HashSet<BS_like_parent_t>();
        }
    
        public int CommentId { get; set; }
        public int PostId { get; set; }
        public int UserId { get; set; }
        public string CommentDate { get; set; }
        public string CommentDetails { get; set; }
    
        public virtual BS_post_parent_t BS_post_parent_t { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BS_dislike_parent_t> BS_dislike_parent_t { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BS_like_parent_t> BS_like_parent_t { get; set; }
        public virtual BS_user_parent_t BS_user_parent_t { get; set; }
    }
}
