//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BS_23.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BS_like_parent_t
    {
        public int LikeId { get; set; }
        public int CommentId { get; set; }
        public int UserId { get; set; }
    
        public virtual BS_comment_parent_t BS_comment_parent_t { get; set; }
        public virtual BS_user_parent_t BS_user_parent_t { get; set; }
    }
}
